apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "talend-vault-sidecar-injector.fullname" . }}
  labels:
{{ include "talend-vault-sidecar-injector.labels" . | indent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "talend-vault-sidecar-injector.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: talend-vault-sidecar-injector
    namespace: {{ .Release.Namespace }}