apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "talend-vault-sidecar-injector.fullname" . }}-mw"
  labels:
{{ include "talend-vault-sidecar-injector.labels" . | indent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{ include "talend-vault-sidecar-injector.fullname" . }}-mw"
    spec:
      restartPolicy: Never
      {{- if .Values.registryKey }}
      imagePullSecrets:
        - name: {{ .Values.registryKey }}
      {{- end }}
      serviceAccountName: talend-vault-sidecar-injector
      containers:
      - name: "{{.Release.Name}}-job-mw"
        image: {{ include "talend-vault-sidecar-injector.hook.image" .Values }}
        imagePullPolicy: {{ .Values.hook.image.pullPolicy }}
        command:
        - "sh"
        - "-c"
        - |
          set -e
          K8S_NAMESPACE={{ .Release.Namespace }}
          VAULTINJECTOR_SA_SECRET=$(kubectl get secrets -n ${K8S_NAMESPACE} -o name | grep -m 1 talend-vault-sidecar-injector-token)
          CA_BUNDLE=$(kubectl get -n ${K8S_NAMESPACE} ${VAULTINJECTOR_SA_SECRET} -o jsonpath='{.data.ca\.crt}')

          if [[ ${CA_BUNDLE} == '' ]]; then
              echo "ERROR: CA_BUNDLE is empty!" >&2
              exit 1
          fi
          
          cat <<EOF | kubectl -n ${K8S_NAMESPACE} apply -f -
          apiVersion: admissionregistration.k8s.io/v1beta1
          kind: MutatingWebhookConfiguration
          metadata:
            name: talend-vault-sidecar-injector-{{ .Release.Namespace }}
            labels:
{{ include "talend-vault-sidecar-injector.labels" . | indent 14 }}
          webhooks:
            - name: vault-sidecar-injector.talend.org
              clientConfig:
                service:
                  name: {{ include "talend-vault-sidecar-injector.service.name" . }}
                  namespace: ${K8S_NAMESPACE}
                  path: "/mutate"
                caBundle: "${CA_BUNDLE}"
              rules:
                - operations: [ "CREATE" ]
                  apiGroups: [""]
                  apiVersions: ["v1"]
                  resources: ["pods"]
              failurePolicy: {{ include "talend-vault-sidecar-injector.failurePolicy" .Values }}
{{ include "talend-vault-sidecar-injector.namespaceSelector" . | indent 14 }}
          EOF
