apiVersion: batch/v1
kind: Job
metadata:
  name: "{{ include "talend-vault-sidecar-injector.fullname" . }}-del"
  labels:
{{ include "talend-vault-sidecar-injector.labels" . | indent 4 }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "-1"
    "helm.sh/hook-delete-policy": hook-succeeded,hook-failed
spec:
  template:
    metadata:
      name: "{{ include "talend-vault-sidecar-injector.fullname" . }}-del"
    spec:
      restartPolicy: Never
      imagePullSecrets:
        - name: {{ include "talend-vault-sidecar-injector.registryKey" .Values }}
      serviceAccountName: talend-vault-sidecar-injector
      containers:
      - name: "{{.Release.Name}}-job-del"
        image: {{ include "talend-vault-sidecar-injector.hook.image" .Values }}
        imagePullPolicy: {{ .Values.hook.image.pullPolicy }}
        command:
        - "sh"
        - "-c"
        - |
          set -e
          kubectl delete mutatingwebhookconfigurations.admissionregistration.k8s.io talend-vault-sidecar-injector-{{ .Release.Namespace }} || true
          kubectl delete secrets -n {{ .Release.Namespace }} {{ include "talend-vault-sidecar-injector.service.name" . }}-{{ .Release.Namespace }}-certs || true
