apiVersion: {{ include "mutatingwebhookconfiguration.apiversion" . }}
kind: MutatingWebhookConfiguration
metadata:
  name: {{ include "talend-vault-sidecar-injector.fullname" . }}
  labels:
{{ include "talend-vault-sidecar-injector.labels" . | indent 4 }}
webhooks:
  - name: vault-sidecar-injector.talend.org
    clientConfig:
      service:
        name: {{ include "talend-vault-sidecar-injector.service.name" . }}
        namespace: {{ .Release.Namespace }}
        path: "/mutate"
    rules:
      - operations: [ "CREATE" ]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
{{- if semverCompare ">=1.16" .Capabilities.KubeVersion.Version }}
    admissionReviewVersions: ["v1", "v1beta1"]
    sideEffects: None
{{- end }}
    failurePolicy: {{ include "talend-vault-sidecar-injector.failurePolicy" .Values }}
{{ include "talend-vault-sidecar-injector.namespaceSelector" . | indent 4 }}