apiVersion: v1
kind: Service
metadata:
  # BEWARE that shared services should not be prefixed with the Helm release name.
  # Please check .Values.service.prefixWithHelmRelease
  name: {{ include "talend-vault-sidecar-injector.service.name" . }}
  labels:
{{ include "talend-vault-sidecar-injector.labels" . | indent 4 }}
{{- if .Values.image.metricsPort }}
    prometheus: "true"
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: https
      port: {{ .Values.service.exposedServicePort }}
      targetPort: https
    {{- if .Values.image.metricsPort }}
    - name: http-metrics
      port: {{ .Values.image.metricsPort }}
      targetPort: http-metrics
    {{- end }}
  selector:
    com.talend.application: {{ .Values.image.applicationNameLabel }}
    com.talend.service: {{ .Values.image.serviceNameLabel }}
    release: {{ .Release.Name }}
