apiVersion: v2
name: vault-sidecar-injector
description: A Helm chart for Talend Vault Sidecar Injector (OSS)
version: 0.0.0
icon: https://www.talend.com/favicon-196x196.png
keywords:
   - Talend
   - vault
   - sidecar
   - vault-sidecar-injector
home: https://www.talend.com/products/
sources:
   - https://github.com/Talend/vault-sidecar-injector
maintainers:
   - name: Talend
     email: support@talend.com
appVersion: 0.0.0