apiVersion: v1
kind: ServiceAccount
metadata:
  name: job-sa
  namespace: default
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-pod-status
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: job-pod-status
subjects:
  - kind: ServiceAccount
    name: job-sa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: job-pod-status
---
apiVersion: batch/v1
kind: Job
metadata:
  name: app6-job
  namespace: default
spec:
  backoffLimit: 1
  template:
    metadata:
      annotations:
        sidecar.vault.talend.org/inject: "true"
        sidecar.vault.talend.org/secrets-type: "static" # static secrets
        # When dealing with static secrets: no need to explicitly enable 'job' mode. You can remove annotation below
        sidecar.vault.talend.org/mode: "job" # Explicitly enable 'job' mode (will also enable 'secrets' mode).
      labels:
        com.talend.application: test
        com.talend.service: test-app-svc
    spec:
      restartPolicy: Never
      # custom serviceAccountName with role allowing to perform GET on pods (needed to poll for job's pod status)
      serviceAccountName: job-sa
      containers:
        - name: app6-job-container
          image: busybox:1.28
          command:
            - "sh"
            - "-c"
            - |
              set -e
              echo "Job started"
              echo "I am a job... still working - 1"
              cat /opt/talend/secrets/secrets.properties
              sleep 5
              echo "I am a job... still working - 2"
              cat /opt/talend/secrets/secrets.properties
              sleep 5
              echo "I am a job... still working - 3"
              cat /opt/talend/secrets/secrets.properties
              sleep 5
              echo "I am a job... still working - 4"
              cat /opt/talend/secrets/secrets.properties
              sleep 5
              echo "I am a job... still working - 5"
              cat /opt/talend/secrets/secrets.properties
              echo "Job stopped"
