apiVersion: apps/v1
kind: Deployment
metadata:
  name: app9
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      com.talend.application: test
      com.talend.service: test-app-svc
  template:
    metadata:
      annotations:
        sidecar.vault.talend.org/inject: "true"
      labels:
        com.talend.application: test
        com.talend.service: test-app-svc
    spec:
      serviceAccountName: default
      containers:
        - name: app9-container
          image: busybox:1.28
          command:
            - "sh"
            - "-c"
            - >
              while true;do echo "My secrets are: $(cat /my-custom-secrets-folder/secrets.properties)"; sleep 5; done
          volumeMounts:
            - name: secrets
              mountPath: /my-custom-secrets-folder
      volumes:
        - name: secrets
          emptyDir:
            medium: Memory
